C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.20.2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapfint (fintf2pywrap, x1, x2, x3, y1, y2, y
     &3, xfit)
      external fint
      real x1
      real x2
      real x3
      real y1
      real y2
      real y3
      real xfit
      real fintf2pywrap, fint
      fintf2pywrap = fint(x1, x2, x3, y1, y2, y3, xfit)
      end


      subroutine f2pyinitdipole(setupfunc)
      external setupfunc
      real colat
      real elon
      real vp
      real ctp
      real stp
      common /dipole/ colat,elon,vp,ctp,stp
      call setupfunc(colat,elon,vp,ctp,stp)
      end

      subroutine f2pyinitfldcomd(setupfunc)
      external setupfunc
      real bx
      real by
      real bz
      real bb
      common /fldcomd/ bx,by,bz,bb
      call setupfunc(bx,by,bz,bb)
      end

      subroutine f2pyinitapxin(setupfunc)
      external setupfunc
      real yapx(3,3)
      common /apxin/ yapx
      call setupfunc(yapx)
      end

      subroutine f2pyinititra(setupfunc)
      external setupfunc
      integer nstp
      real y(3)
      real yp(3)
      real sgn
      real ds
      common /itra/ nstp,y,yp,sgn,ds
      call setupfunc(nstp,y,yp,sgn,ds)
      end

      subroutine f2pyinitmagcof(setupfunc)
      external setupfunc
      integer nmax
      real gb(255)
      real gv(225)
      integer ichg
      common /magcof/ nmax,gb,gv,ichg
      call setupfunc(nmax,gb,gv,ichg)
      end


