language: python

python:
{% for env, config in tox_environments|dictsort %}{% if not config.cover %}
  - "{{ config.python[-3:] }}"
{% endif %}{% endfor %}

sudo: false

addons:
  apt:
    packages:
    - gfortran

before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - pip install tox-travis

install:
  - python setup.py clean --all build_ext --force --inplace
  - python setup.py install

script:
  - tox

after_success:
  - coveralls --rcfile=setup.cfg

notifications:
  email:
    on_success: never
    on_failure: always
