# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/
# using-python-with-github-actions

name: pytest on Windows

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    env:
       FC: gfortran

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} with Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Install standard and test dependencies
      shell: bash -l {0}
      run: conda install -q -c msys2 m2w64-toolchain coveralls numpy pytest<=6.2.5 pytest-cov scipy

    - name: Install on Windows
      shell: bash -l {0}
      run: python setup.py config --compiler=mingw32 --fcompiler=gfortran install

    - name: Run unit and integration tests
      shell: bash -l {0}
      run: pytest --cov=src

    - name: Publish results to coveralls upon success
      shell: bash -l {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --rcfile=setup.cfg --service=github
